/*
 * This file is generated by jOOQ.
 */
package dgroomes.db.tables.records;


import dgroomes.db.tables.Observations;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ObservationsRecord extends UpdatableRecordImpl<ObservationsRecord> implements Record2<Integer, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>observations.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>observations.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>observations.observation</code>.
     */
    public void setObservation(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>observations.observation</code>.
     */
    public String getObservation() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Integer, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Observations.OBSERVATIONS.ID;
    }

    @Override
    public Field<String> field2() {
        return Observations.OBSERVATIONS.OBSERVATION;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getObservation();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getObservation();
    }

    @Override
    public ObservationsRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public ObservationsRecord value2(String value) {
        setObservation(value);
        return this;
    }

    @Override
    public ObservationsRecord values(Integer value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ObservationsRecord
     */
    public ObservationsRecord() {
        super(Observations.OBSERVATIONS);
    }

    /**
     * Create a detached, initialised ObservationsRecord
     */
    public ObservationsRecord(Integer id, String observation) {
        super(Observations.OBSERVATIONS);

        setId(id);
        setObservation(observation);
    }

    /**
     * Create a detached, initialised ObservationsRecord
     */
    public ObservationsRecord(dgroomes.db.tables.pojos.Observations value) {
        super(Observations.OBSERVATIONS);

        if (value != null) {
            setId(value.getId());
            setObservation(value.getObservation());
        }
    }
}
