/*
 * This file is generated by jOOQ.
 */
package dgroomes.db;


import dgroomes.db.tables.ObservationTypes;
import dgroomes.db.tables.Observations;


/**
 * Convenience access to all tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>observation_types</code>.
     */
    public static final ObservationTypes OBSERVATION_TYPES = ObservationTypes.OBSERVATION_TYPES;

    /**
     * The table <code>observations</code>.
     */
    public static final Observations OBSERVATIONS = Observations.OBSERVATIONS;
}
