/*
 * This file is generated by jOOQ.
 */
package dgroomes.db.tables;


import dgroomes.db.DefaultSchema;
import dgroomes.db.Keys;
import dgroomes.db.tables.records.ObservationTypesRecord;

import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function2;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ObservationTypes extends TableImpl<ObservationTypesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>observation_types</code>
     */
    public static final ObservationTypes OBSERVATION_TYPES = new ObservationTypes();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ObservationTypesRecord> getRecordType() {
        return ObservationTypesRecord.class;
    }

    /**
     * The column <code>observation_types.id</code>.
     */
    public final TableField<ObservationTypesRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>observation_types.description</code>.
     */
    public final TableField<ObservationTypesRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.CLOB.nullable(false), this, "");

    private ObservationTypes(Name alias, Table<ObservationTypesRecord> aliased) {
        this(alias, aliased, null);
    }

    private ObservationTypes(Name alias, Table<ObservationTypesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>observation_types</code> table reference
     */
    public ObservationTypes(String alias) {
        this(DSL.name(alias), OBSERVATION_TYPES);
    }

    /**
     * Create an aliased <code>observation_types</code> table reference
     */
    public ObservationTypes(Name alias) {
        this(alias, OBSERVATION_TYPES);
    }

    /**
     * Create a <code>observation_types</code> table reference
     */
    public ObservationTypes() {
        this(DSL.name("observation_types"), null);
    }

    public <O extends Record> ObservationTypes(Table<O> child, ForeignKey<O, ObservationTypesRecord> key) {
        super(child, key, OBSERVATION_TYPES);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public UniqueKey<ObservationTypesRecord> getPrimaryKey() {
        return Keys.OBSERVATION_TYPES__PK_OBSERVATION_TYPES;
    }

    @Override
    public ObservationTypes as(String alias) {
        return new ObservationTypes(DSL.name(alias), this);
    }

    @Override
    public ObservationTypes as(Name alias) {
        return new ObservationTypes(alias, this);
    }

    @Override
    public ObservationTypes as(Table<?> alias) {
        return new ObservationTypes(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ObservationTypes rename(String name) {
        return new ObservationTypes(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ObservationTypes rename(Name name) {
        return new ObservationTypes(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ObservationTypes rename(Table<?> name) {
        return new ObservationTypes(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function2<? super Integer, ? super String, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function2<? super Integer, ? super String, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
