/*
 * This file is generated by jOOQ.
 */
package dgroomes.db.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ObservationTypes implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer id;
    private String description;

    public ObservationTypes() {}

    public ObservationTypes(ObservationTypes value) {
        this.id = value.id;
        this.description = value.description;
    }

    public ObservationTypes(
        Integer id,
        String description
    ) {
        this.id = id;
        this.description = description;
    }

    /**
     * Getter for <code>observation_types.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>observation_types.id</code>.
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * Getter for <code>observation_types.description</code>.
     */
    public String getDescription() {
        return this.description;
    }

    /**
     * Setter for <code>observation_types.description</code>.
     */
    public void setDescription(String description) {
        this.description = description;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final ObservationTypes other = (ObservationTypes) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.description == null) {
            if (other.description != null)
                return false;
        }
        else if (!this.description.equals(other.description))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.description == null) ? 0 : this.description.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ObservationTypes (");

        sb.append(id);
        sb.append(", ").append(description);

        sb.append(")");
        return sb.toString();
    }
}
